name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./   # Set the working directory for all steps

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before || github.sha }}  # Use the commit before for push events

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install   # or yarn install, depending on your project

      - name: Run lint
        run: chmod +x ./gradlew lintDebug

      - name: Upload lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: app/build/reports/lint-results-debug.html